import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./strict.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  preload: true,
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  // This font is used for code blocks; avoid preloading to prevent unused-preload warnings.
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.className} ${geistMono.variable} bg-background text-foreground min-h-screen`}>
        {children}
      </body>
    </html>
  );
}
